// Categorías para los filtros
export const categories = [
  { id: 'todos', name: 'Todos' },
  { id: 'hidratantes', name: 'Hidratantes' },
  { id: 'relajantes', name: 'Relajantes' },
  { id: 'tonificantes', name: 'Tonificantes' },
  { id: 'exfoliantes', name: 'Exfoliantes' },
  { id: 'purificantes', name: 'Purificantes' },
  { id: 'revitalizantes', name: 'Revitalizantes' },
  { id: 'calmantes', name: 'Calmantes' },
];

// Opciones de orden
export const sortOptions = [
  { value: 'popular', label: 'Más populares' },
  { value: 'newest', label: 'Más nuevos' },
  { value: 'price-low', label: 'Precio: Bajo a alto' },
  { value: 'price-high', label: 'Precio: Alto a bajo' },
];

// Datos de ejemplo - En una app real vendrían de una API o base de datos
export const luxuryProducts = [
  {
    id: 1,
    name: 'Lavanda Provence',
    description:
      'Relajante y calmante, una experiencia de tranquilidad para pieles sensibles.',
    price: 12.99,
    image: '/img/jabon.jpg',
    featured: true,
    category: 'Relajantes',
    ingredients: [
      'Aceite de oliva virgen',
      'Aceite de coco',
      'Lavanda orgánica',
      'Arcilla violeta',
      'Manteca de karité',
    ],
    isNew: false,
    rating: 4.8,
    reviews: 124,
    colors: ['#e0d5f0', '#c9b8e0'],
    bg: 'bg-gradient-to-b from-purple-100 to-purple-50',
    accent: 'text-purple-800',
    border: 'border-purple-200',
    badgeText: 'Relajante',
    stock: 15,
  },
  {
    id: 2,
    name: 'Aloe Vera Royal',
    description:
      'Hidratante intensivo que nutre y repara la piel dañada o expuesta al sol.',
    price: 14.99,
    image: '/img/productos/11.jpg',
    category: 'Hidratantes',
    featured: true,
    ingredients: [
      'Aceite de oliva virgen',
      'Aceite de argán',
      'Gel de aloe vera orgánico',
      'Aceite esencial de menta',
      'Vitamina E',
    ],
    isNew: true,
    rating: 4.9,
    reviews: 87,
    colors: ['#d4f0d9', '#b3e0b9'],
    bg: 'bg-gradient-to-b from-green-100 to-green-50',
    accent: 'text-green-800',
    border: 'border-green-200',
    badgeText: 'Hidratante',
    stock: 10,
  },
  {
    id: 3,
    name: 'Rosa Damascena',
    description:
      'El aroma atemporal de rosas frescas con propiedades tonificantes para tu piel.',
    price: 16.99,
    image: '/img/productos/2.jpg',
    category: 'Tonificantes',
    featured: true,
    ingredients: [
      'Aceite de oliva virgen',
      'Manteca de karité',
      'Pétalos de rosa orgánicos',
      'Arcilla rosa',
      'Agua de rosas',
    ],
    isNew: false,
    rating: 4.7,
    reviews: 105,
    colors: ['#f8d4e2', '#f0b8d0'],
    bg: 'bg-gradient-to-b from-rose-100 to-rose-50',
    accent: 'text-rose-800',
    border: 'border-rose-200',
    badgeText: 'Tonificante',
    stock: 8,
  },
  {
    id: 4,
    name: 'Miel & Avena Luxury',
    description:
      'Exfoliación suave con nutrición profunda. Una caricia para todo tipo de pieles.',
    price: 15.99,
    image: '/img/products/honey-soap.png',
    category: 'Exfoliantes',
    featured: false,
    ingredients: [
      'Aceite de oliva virgen',
      'Miel de acacia orgánica',
      'Avena',
      'Manteca de cacao',
      'Vainilla',
    ],
    isNew: true,
    rating: 4.9,
    reviews: 62,
    colors: ['#f0e4c9', '#e0d0a8'],
    bg: 'bg-gradient-to-b from-amber-100 to-amber-50',
    accent: 'text-amber-800',
    border: 'border-amber-200',
    badgeText: 'Nutritivo',
    stock: 12,
  },
  {
    id: 5,
    name: 'Arcilla Verde Detox',
    description:
      'Desintoxicante profundo para pieles grasas o con impurezas. Limpieza purificante.',
    price: 13.99,
    image: '/img/products/green-clay-soap.png',
    category: 'Purificantes',
    featured: false,
    ingredients: [
      'Aceite de oliva virgen',
      'Arcilla verde francesa',
      'Aceite de árbol de té',
      'Carbón activado',
      'Menta',
    ],
    isNew: false,
    rating: 4.6,
    reviews: 78,
    colors: ['#c9e6d9', '#a8d0b9'],
    bg: 'bg-gradient-to-b from-emerald-100 to-emerald-50',
    accent: 'text-emerald-800',
    border: 'border-emerald-200',
    badgeText: 'Purificante',
    stock: 7,
  },
  {
    id: 6,
    name: 'Cítricos Mediterráneos',
    description:
      'Revitalizante mezcla de cítricos que despierta los sentidos y energiza tu día.',
    price: 14.49,
    image: '/img/products/citrus-soap.png',
    category: 'Revitalizantes',
    featured: false,
    ingredients: [
      'Aceite de oliva virgen',
      'Manteca de cacao',
      'Naranja orgánica',
      'Limón',
      'Pomelo',
    ],
    isNew: true,
    rating: 4.8,
    reviews: 45,
    colors: ['#f9e8c0', '#f7d692'],
    bg: 'bg-gradient-to-b from-orange-100 to-orange-50',
    accent: 'text-orange-800',
    border: 'border-orange-200',
    badgeText: 'Energizante',
    stock: 20,
  },
  {
    id: 7,
    name: 'Caléndula Soothing',
    description:
      'Calmante para pieles irritadas o con problemas. Alivio natural para dermatitis.',
    price: 15.49,
    image: '/img/products/calendula-soap.png',
    featured: false,
    category: 'Calmantes',
    ingredients: [
      'Aceite de oliva virgen',
      'Caléndula orgánica',
      'Manzanilla',
      'Manteca de karité',
      'Avena',
    ],
    isNew: false,
    rating: 4.9,
    reviews: 92,
    colors: ['#f8e3c5', '#f5d49e'],
    bg: 'bg-gradient-to-b from-yellow-100 to-yellow-50',
    accent: 'text-yellow-800',
    border: 'border-yellow-200',
    badgeText: 'Calmante',
    stock: 5,
  },
  {
    id: 8,
    name: 'Coco Tropical',
    description:
      'Ultra hidratante para pieles secas. El placer tropical para una piel suave y perfumada.',
    price: 12.99,
    image: '/img/products/coconut-soap.png',
    featured: false,
    category: 'Hidratantes',
    ingredients: [
      'Aceite de coco virgen',
      'Aceite de oliva',
      'Leche de coco',
      'Manteca de cacao',
      'Vainilla',
    ],
    isNew: false,
    rating: 4.7,
    reviews: 84,
    colors: ['#e8e8e8', '#d4d4d4'],
    bg: 'bg-gradient-to-b from-neutral-100 to-neutral-50',
    accent: 'text-neutral-800',
    border: 'border-neutral-200',
    badgeText: 'Hidratante',
    stock: 14,
  },
];
