export const categories = [
  { id: 'todos', name: 'Todos' },
  { id: 'hidratantes', name: 'Hidratantes' },
  { id: 'relajantes', name: 'Relajantes' },
  { id: 'tonificantes', name: 'Tonificantes' },
  { id: 'exfoliantes', name: 'Exfoliantes' },
  { id: 'purificantes', name: 'Purificantes' },
  { id: 'revitalizantes', name: 'Revitalizantes' },
  { id: 'calmantes', name: 'Calmantes' },
];

export const sortOptions = [
  { value: 'popular', label: 'Más populares' },
  { value: 'newest', label: 'Más nuevos' },
  { value: 'price-low', label: 'Precio: Bajo a alto' },
  { value: 'price-high', label: 'Precio: Alto a bajo' },
];

export const luxuryProducts = [
  {
    id: 1,
    name: 'Jabon de Lavanda',
    description:
      'Tiene efectos calmantes y relajantes... Ideal para la piel grasa y mixta, uso diario en rostro y cuerpo.',
    price: 12.99,
    image: '/img/productos/jabon-9.jpg',
    featured: true,
    category: 'Relajantes',
    ingredients: ['Aceite esencial de lavanda', 'Vitamina E'],
    isNew: false,
    rating: 4.8,
    reviews: 124,
    colors: ['#e0d5f0', '#c9b8e0'],
    bg: 'bg-gradient-to-b from-purple-100 to-purple-50',
    accent: 'text-purple-800',
    border: 'border-purple-200',
    badgeText: 'Relajante',
    stock: 15,
  },
  {
    id: 2,
    name: 'Jabon de carbon activado',
    description:
      'Limpia profundamente y blanquea Ideal para piel grasa y con acne. Uso interdiario solo rostro',
    price: 14.99,
    image: '/img/productos/jabon_de_carbon_activado.webp',
    category: 'Hidratantes',
    featured: true,
    ingredients: ['Gliserina vegetal', 'Vitamina E', 'Manteca de karite'],
    isNew: true,
    rating: 4.9,
    reviews: 87,
    colors: ['#d4f0d9', '#b3e0b9'],
    bg: 'bg-gradient-to-b from-green-100 to-green-50',
    accent: 'text-green-800',
    border: 'border-green-200',
    badgeText: 'Hidratante',
    stock: 10,
  },
  {
    id: 3,
    name: 'Jabon de coco y avena',
    description:
      'Ideal pieles sensibles y secas. Estimula la produccion de  colageno. Pieles mixta y normal. Uso rostro y cuerpo',
    price: 16.99,
    image: '/img/productos/jabon-11.jpg',
    category: 'Tonificantes',
    featured: true,
    ingredients: ['Gliserina vegetal', 'Vitamina E'],
    isNew: false,
    rating: 4.7,
    reviews: 105,
    colors: ['#f8d4e2', '#f0b8d0'],
    bg: 'bg-gradient-to-b from-rose-100 to-rose-50',
    accent: 'text-rose-800',
    border: 'border-rose-200',
    badgeText: 'Tonificante',
    stock: 8,
  },
  {
    id: 4,
    name: 'Jabon de chocolate y almendra',
    description:
      'Exfoliación suave con nutrición profunda. Una caricia para todo tipo de pieles.',
    price: 15.99,
    image: '/img/productos/jabon-7.jpg',
    category: 'Exfoliantes',
    featured: false,
    ingredients: ['Gliserina vegetal'],
    isNew: true,
    rating: 4.9,
    reviews: 62,
    colors: ['#f0e4c9', '#e0d0a8'],
    bg: 'bg-gradient-to-b from-amber-100 to-amber-50',
    accent: 'text-amber-800',
    border: 'border-amber-200',
    badgeText: 'Nutritivo',
    stock: 12,
  },
  {
    id: 5,
    name: 'Jabon de romero y miel',
    description:
      'Rejuvenece tonifica pieles mixtas y secas. Uso para rostro y cuerpo',
    price: 13.99,
    image: '/img/productos/jabon-7.jpg',
    category: 'Revitalizantes',
    featured: false,
    ingredients: ['Gliserina vegetal', 'Vitamina E'],
    isNew: false,
    rating: 4.6,
    reviews: 78,
    colors: ['#c9e6d9', '#a8d0b9'],
    bg: 'bg-gradient-to-b from-emerald-100 to-emerald-50',
    accent: 'text-emerald-800',
    border: 'border-emerald-200',
    badgeText: 'Purificante',
    stock: 7,
  },
  {
    id: 6,
    name: 'Jabon de Curcuma',
    description: 'Limpia,ilumina y tonifica. Uso para rostro y cuerpo',
    price: 14.49,
    image: '/img/productos/jabon-7.jpg',
    category: 'Tonificantes',
    featured: false,
    ingredients: ['Gliserina vegetal', 'Aceite se sesamo', 'Vitamina E'],
    isNew: true,
    rating: 4.8,
    reviews: 45,
    colors: ['#f9e8c0', '#f7d692'],
    bg: 'bg-gradient-to-b from-orange-100 to-orange-50',
    accent: 'text-orange-800',
    border: 'border-orange-200',
    badgeText: 'Energizante',
    stock: 20,
  },
  {
    id: 7,
    name: 'Jabon intimo de menta y alumbre',
    description: 'Uso solo intimo',
    price: 15.49,
    image: '/img/productos/jabon-8.jpg',
    featured: false,
    category: 'Purificantes',
    ingredients: ['Gliserina vegetal', 'Alumbre', 'Leche de cabra'],
    isNew: false,
    rating: 4.9,
    reviews: 92,
    colors: ['#f8e3c5', '#f5d49e'],
    bg: 'bg-gradient-to-b from-yellow-100 to-yellow-50',
    accent: 'text-yellow-800',
    border: 'border-yellow-200',
    badgeText: 'Calmante',
    stock: 5,
  },
  {
    id: 8,
    name: 'Jabon de juventud',
    description: 'Uso solo rostro',
    price: 12.99,
    image: '/img/productos/jabon-10',
    featured: false,
    category: 'Hidratantes',
    ingredients: ['Gliserina vegetal', 'Aceite rosa mozqueta', 'Rosas'],
    isNew: false,
    rating: 4.7,
    reviews: 84,
    colors: ['#e8e8e8', '#d4d4d4'],
    bg: 'bg-gradient-to-b from-neutral-100 to-neutral-50',
    accent: 'text-neutral-800',
    border: 'border-neutral-200',
    badgeText: 'Hidratante',
    stock: 14,
  },
];

// Reseñas ficticias
export const productReviews = [
  {
    id: 1,
    author: 'Laura Martínez',
    date: '15/03/2023',
    rating: 5,
    review:
      'Increíble este jabón. Mi piel se siente hidratada y suave después de usarlo. El aroma es delicado y agradable. Definitivamente lo compraré de nuevo.',
    avatar: '/img/testimonials/avatar-1.jpg',
  },
  {
    id: 2,
    author: 'Carlos Rodríguez',
    date: '27/04/2023',
    rating: 4,
    review:
      'Muy buen producto. Lo uso desde hace un mes y he notado una mejora significativa en mi piel. Solo le quito una estrella porque el tamaño podría ser un poco más grande por el precio.',
    avatar: '/img/testimonials/avatar-2.jpg',
  },
  {
    id: 3,
    author: 'Elena García',
    date: '10/05/2023',
    rating: 5,
    review:
      'Absolutamente enamorada de este jabón. Es perfecto para mi piel sensible, no irrita en absoluto y deja una sensación refrescante. El envase eco-friendly es un gran plus.',
    avatar: '/img/testimonials/avatar-3.jpg',
  },
];
